using System;
using System.Text;
namespace WindowsFormsApplication2
{
	internal class ImportantFunctions
	{
		public string nothing_to_see_here = "IH4+HpDgiVwQj2rBRxZyLVgVTiQFxFjXMqcC4U8kPrF4zm9I3NBtaol9hChF1Hvt3+bEqW5tujSPHW6XO50tsALNmrgjO0taLpZ4FOrrOJPI1i6VP747B4ixN5/AzLFlNSno+wHiB2dDPgrBw29mXH8pqwvYK7k4/3ylpB4NW+p012s8qCt7eqeEQFURgQz53qoO5TCi2VaVzFJkOXpNxCEgKZMIpkWn/yXQrr5mPpDGZpwkBxicd1uQlrNaRZoJJVIz5/pVTXEk7HzO4KWp2kwvJqhdjMWN2m4OyIBWO3QQaIr5Pd5e6DjC26UGdnpzMGBs3mMKEOzrMFrFVNHhNxn3RdLWdCH80KwC0ObaMYn5XrGMWnGrHLTzxqN3kZYtkLED8CxoyWr3jb9Ifer/2ZsW3k9KMbLwlm6mRaWSab3qBI/f07czw1IwoEJ92OrjceLAP8u+NN3bHQSu8u/2qI6hFw8n/vEN29YRB9PhlrKAKpEZv93z9Cb4zf5o73NA1RTi+xZc3UG1mOTNtFeqG7AcyYyMpc/yNJSeaotgNzMgKHFQUQFOBwba3qd5hDjTyW4leoKj38D5Oe/DB4NLBI0cdCqu4RLl0tse5X3BXo0GrXkDxvIhLAZ55GX6FmlfqmCwv1FJcGfK0QqHkMxIUeEuA0N8mrc5bA1q/bh8UxKEzAnAuGlG+jx4w3+Hkv9XFWLEyYX6eHvIJ1DI0mB7TViAX9Xg8WO7qdDkMBbdJnCQsQPwLGjJahSPE1U6BW6BrOdOBDIYuVzPsN8EyGI/dZsW3k9KMbLw/TSHZaGqjNMDkF97OpQbj3DW6FSqTR0F40JJJ92qhQXAMcMyiYMQW2A81d5xCgyDIPlcpgp6ee0H9H8E11aplmMThQHmAFgYecEOJAFAU9Q0qW9e3+KWs192fgl/kpMRtD6HODh7tNRkzph7aBiVldp6GIs/peNePwx6pbCmr/ERInU3GcoxgC1no/siXs2dm0C8A41auBIdH0UGbDVEbMOVlY8+igPW";
		private string AVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVerySecretPieceOfInformation = "N2NhNWRkNzc5MGUwNWFkYQ==";
		private string enc;
		public string hideSomethingUsingASecretyPieceOfInformation()
		{
			string input = "A very secret message here.";
			this.enc = Encryption.Encrypt(input, this.AVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVerySecretPieceOfInformation);
			return this.enc;
		}
		public string extractSomethingUsingASecretyPieceOfInformation()
		{
			return Encryption.Decrypt(this.enc, this.AVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVeryVerySecretPieceOfInformation);
		}
		public string getKey()
		{
			return Encoding.UTF8.GetString(Convert.FromBase64String("YTA0ZjUyZWI4YWI2MmI5NWY0YWFlNDExZTk4YmQzNzVjNjMxZTVkMzZmMzY2Nzc4N2MxMzQ3OTUzZDQ2NTA5Mw=="));
		}
	}
}
